name: Monthly Release

on:
  workflow_call:

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Generate Release Notes
        id: release-notes
        run: |
          RELEASE_NOTES=$(git log --format="- %s" $(git describe --tags --abbrev=0)..HEAD)
          echo "::set-output name=notes::$RELEASE_NOTES"

      - name: Set Tag
        run: |
          TAG_NAME=$(date -u +"%Y-%m-%d")
          git tag $TAG_NAME
          git push origin $TAG_NAME

      - name: Create Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.set-tag.outputs.tag }}
          release_name: Release ${{ steps.set-tag.outputs.tag }}
          body: ${{ steps.release-notes.outputs.notes }}
