name: Automated Change log
on:
  workflow_call:
jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"
      - name: Checkout
        uses: actions/checkout@v2

      - name: conentional changelog action
        id: changelog
        uses: TriPSs/conventional-changelog-action@latest
        with:
          tag-prefix: "hubs-prod"

      - name: create release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: hubs-prod-${{ steps.date.outputs.date }}
          release_name: Release ${{ steps.date.outputs.date }}
          body: ${{ steps.changelog.outputs.changelog }}
          draft: false
          prerelease: false
